version: "3.2"

services:
  nginx:
    image: nginx:1.17.10-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - echarles-front-net
    depends_on:
      - app
    volumes:
      - ./nginx/conf:/etc/nginx
      - ./nginx/www:/var/www

  postgresql:
    image: postgis/postgis:12-3.0
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
      - PGDATA=${PG_DOCKER_DATA_PATH}
    ports:
      - "${POSTGRES_PUBLISED_PORT}:${POSTGRES_PORT}"
    networks:
      - cherry-back-net
    volumes:
      - ${POSTGRES_HOST_DATA_PATH}:${PG_DOCKER_DATA_PATH}
      - ./postgresql/20_cherry.communes.sql:/docker-entrypoint-initdb.d/20_cherry.communes.sql

networks:
  cherry-back-net:
    external: false
  cherry-front-net:
    external: false